// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "ms_store_api.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <cmath>
#include <limits>
#include <map>
#include <optional>
#include <string>

namespace ms_store_trial {
using ::flutter::BasicMessageChannel;
using ::flutter::CustomEncodableValue;
using ::flutter::EncodableList;
using ::flutter::EncodableMap;
using ::flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

namespace {
template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b);

bool PigeonInternalDeepEquals(const double& a, const double& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b);

template<typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b);

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b);

template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b) {
  return a == b;
}

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (size_t i = 0; i < a.size(); ++i) {
    if (!PigeonInternalDeepEquals(a[i], b[i])) {
      return false;
    }
  }
  return true;
}

template <typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (const auto& kv : a) {
    bool found = false;
    for (const auto& b_kv : b) {
      if (PigeonInternalDeepEquals(kv.first, b_kv.first)) {
        if (PigeonInternalDeepEquals(kv.second, b_kv.second)) {
          found = true;
          break;
        } else {
          return false;
        }
      }
    }
    if (!found) {
      return false;
    }
  }
  return true;
}

bool PigeonInternalDeepEquals(const double& a, const double& b) {
  // Normalize -0.0 to 0.0 and handle NaN equality.
  return (a == b) || (std::isnan(a) && std::isnan(b));
}

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b) {
  if (!a && !b) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b) {
  if (a.get() == b.get()) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b) {
  if (a.index() != b.index()) {
    return false;
  }
  if (const double* da = std::get_if<double>(&a)) {
    return PigeonInternalDeepEquals(*da, std::get<double>(b));
  } else if (const ::flutter::EncodableList* la = std::get_if<::flutter::EncodableList>(&a)) {
    return PigeonInternalDeepEquals(*la, std::get<::flutter::EncodableList>(b));
  } else if (const ::flutter::EncodableMap* ma = std::get_if<::flutter::EncodableMap>(&a)) {
    return PigeonInternalDeepEquals(*ma, std::get<::flutter::EncodableMap>(b));
  }
  return a == b;
}

template <typename T>
size_t PigeonInternalDeepHash(const T& v);

size_t PigeonInternalDeepHash(const double& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v);

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v);

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v);

template <typename T>
size_t PigeonInternalDeepHash(const T& v) {
  return std::hash<T>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v) {
  size_t result = 1;
  for (const auto& item : v) {
    result = result * 31 + PigeonInternalDeepHash(item);
  }
  return result;
}

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v) {
  size_t result = 0;
  for (const auto& kv : v) {
    result += ((PigeonInternalDeepHash(kv.first) * 31) ^ PigeonInternalDeepHash(kv.second));
  }
  return result;
}

size_t PigeonInternalDeepHash(const double& v) {
  if (std::isnan(v)) {
    // Normalize NaN to a consistent hash.
    return std::hash<double>()(std::numeric_limits<double>::quiet_NaN());
  }
  if (v == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return std::hash<double>()(0.0);
  }
  return std::hash<double>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v) {
  size_t result = v.index();
  if (const double* dv = std::get_if<double>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*dv);
  } else if (const ::flutter::EncodableList* lv =
                 std::get_if<::flutter::EncodableList>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*lv);
  } else if (const ::flutter::EncodableMap* mv =
                 std::get_if<::flutter::EncodableMap>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*mv);
  } else {
    std::visit(
        [&result](const auto& val) {
          using T = std::decay_t<decltype(val)>;
          if constexpr (!std::is_same_v<T, double> &&
                        !std::is_same_v<T, ::flutter::EncodableList> &&
                        !std::is_same_v<T, ::flutter::EncodableMap> &&
                        !std::is_same_v<T, std::monostate> &&
                        !std::is_same_v<T, ::flutter::CustomEncodableValue>) {
            result = result * 31 + PigeonInternalDeepHash(val);
          }
        },
        v);
  }
  return result;
}

}  // namespace
// MsStoreAppLicense

MsStoreAppLicense::MsStoreAppLicense(
  bool is_active,
  bool is_trial,
  bool is_trial_owned_by_this_user,
  int64_t trial_time_remaining,
  int64_t expiration_timestamp,
  const std::string& sku_store_id,
  const std::string& extended_json_data,
  const std::string& trial_unique_id)
 : is_active_(is_active),
    is_trial_(is_trial),
    is_trial_owned_by_this_user_(is_trial_owned_by_this_user),
    trial_time_remaining_(trial_time_remaining),
    expiration_timestamp_(expiration_timestamp),
    sku_store_id_(sku_store_id),
    extended_json_data_(extended_json_data),
    trial_unique_id_(trial_unique_id) {}

bool MsStoreAppLicense::is_active() const {
  return is_active_;
}

void MsStoreAppLicense::set_is_active(bool value_arg) {
  is_active_ = value_arg;
}


bool MsStoreAppLicense::is_trial() const {
  return is_trial_;
}

void MsStoreAppLicense::set_is_trial(bool value_arg) {
  is_trial_ = value_arg;
}


bool MsStoreAppLicense::is_trial_owned_by_this_user() const {
  return is_trial_owned_by_this_user_;
}

void MsStoreAppLicense::set_is_trial_owned_by_this_user(bool value_arg) {
  is_trial_owned_by_this_user_ = value_arg;
}


int64_t MsStoreAppLicense::trial_time_remaining() const {
  return trial_time_remaining_;
}

void MsStoreAppLicense::set_trial_time_remaining(int64_t value_arg) {
  trial_time_remaining_ = value_arg;
}


int64_t MsStoreAppLicense::expiration_timestamp() const {
  return expiration_timestamp_;
}

void MsStoreAppLicense::set_expiration_timestamp(int64_t value_arg) {
  expiration_timestamp_ = value_arg;
}


const std::string& MsStoreAppLicense::sku_store_id() const {
  return sku_store_id_;
}

void MsStoreAppLicense::set_sku_store_id(std::string_view value_arg) {
  sku_store_id_ = value_arg;
}


const std::string& MsStoreAppLicense::extended_json_data() const {
  return extended_json_data_;
}

void MsStoreAppLicense::set_extended_json_data(std::string_view value_arg) {
  extended_json_data_ = value_arg;
}


const std::string& MsStoreAppLicense::trial_unique_id() const {
  return trial_unique_id_;
}

void MsStoreAppLicense::set_trial_unique_id(std::string_view value_arg) {
  trial_unique_id_ = value_arg;
}


EncodableList MsStoreAppLicense::ToEncodableList() const {
  EncodableList list;
  list.reserve(8);
  list.push_back(EncodableValue(is_active_));
  list.push_back(EncodableValue(is_trial_));
  list.push_back(EncodableValue(is_trial_owned_by_this_user_));
  list.push_back(EncodableValue(trial_time_remaining_));
  list.push_back(EncodableValue(expiration_timestamp_));
  list.push_back(EncodableValue(sku_store_id_));
  list.push_back(EncodableValue(extended_json_data_));
  list.push_back(EncodableValue(trial_unique_id_));
  return list;
}

MsStoreAppLicense MsStoreAppLicense::FromEncodableList(const EncodableList& list) {
  MsStoreAppLicense decoded(
    std::get<bool>(list[0]),
    std::get<bool>(list[1]),
    std::get<bool>(list[2]),
    std::get<int64_t>(list[3]),
    std::get<int64_t>(list[4]),
    std::get<std::string>(list[5]),
    std::get<std::string>(list[6]),
    std::get<std::string>(list[7]));
  return decoded;
}

bool MsStoreAppLicense::operator==(const MsStoreAppLicense& other) const {
  return PigeonInternalDeepEquals(is_active_, other.is_active_) && PigeonInternalDeepEquals(is_trial_, other.is_trial_) && PigeonInternalDeepEquals(is_trial_owned_by_this_user_, other.is_trial_owned_by_this_user_) && PigeonInternalDeepEquals(trial_time_remaining_, other.trial_time_remaining_) && PigeonInternalDeepEquals(expiration_timestamp_, other.expiration_timestamp_) && PigeonInternalDeepEquals(sku_store_id_, other.sku_store_id_) && PigeonInternalDeepEquals(extended_json_data_, other.extended_json_data_) && PigeonInternalDeepEquals(trial_unique_id_, other.trial_unique_id_);
}

bool MsStoreAppLicense::operator!=(const MsStoreAppLicense& other) const {
  return !(*this == other);
}

size_t MsStoreAppLicense::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(is_active_);
  result = result * 31 + PigeonInternalDeepHash(is_trial_);
  result = result * 31 + PigeonInternalDeepHash(is_trial_owned_by_this_user_);
  result = result * 31 + PigeonInternalDeepHash(trial_time_remaining_);
  result = result * 31 + PigeonInternalDeepHash(expiration_timestamp_);
  result = result * 31 + PigeonInternalDeepHash(sku_store_id_);
  result = result * 31 + PigeonInternalDeepHash(extended_json_data_);
  result = result * 31 + PigeonInternalDeepHash(trial_unique_id_);
  return result;
}

size_t PigeonInternalDeepHash(const MsStoreAppLicense& v) {
  return v.Hash();
}

// MsStoreProduct

MsStoreProduct::MsStoreProduct(
  const std::string& store_id,
  const std::string& title,
  const std::string& description,
  const std::string& price,
  const std::string& price_currency_code,
  const std::string& formatted_price,
  const std::string& product_kind,
  const std::string& extended_json_data)
 : store_id_(store_id),
    title_(title),
    description_(description),
    price_(price),
    price_currency_code_(price_currency_code),
    formatted_price_(formatted_price),
    product_kind_(product_kind),
    extended_json_data_(extended_json_data) {}

const std::string& MsStoreProduct::store_id() const {
  return store_id_;
}

void MsStoreProduct::set_store_id(std::string_view value_arg) {
  store_id_ = value_arg;
}


const std::string& MsStoreProduct::title() const {
  return title_;
}

void MsStoreProduct::set_title(std::string_view value_arg) {
  title_ = value_arg;
}


const std::string& MsStoreProduct::description() const {
  return description_;
}

void MsStoreProduct::set_description(std::string_view value_arg) {
  description_ = value_arg;
}


const std::string& MsStoreProduct::price() const {
  return price_;
}

void MsStoreProduct::set_price(std::string_view value_arg) {
  price_ = value_arg;
}


const std::string& MsStoreProduct::price_currency_code() const {
  return price_currency_code_;
}

void MsStoreProduct::set_price_currency_code(std::string_view value_arg) {
  price_currency_code_ = value_arg;
}


const std::string& MsStoreProduct::formatted_price() const {
  return formatted_price_;
}

void MsStoreProduct::set_formatted_price(std::string_view value_arg) {
  formatted_price_ = value_arg;
}


const std::string& MsStoreProduct::product_kind() const {
  return product_kind_;
}

void MsStoreProduct::set_product_kind(std::string_view value_arg) {
  product_kind_ = value_arg;
}


const std::string& MsStoreProduct::extended_json_data() const {
  return extended_json_data_;
}

void MsStoreProduct::set_extended_json_data(std::string_view value_arg) {
  extended_json_data_ = value_arg;
}


EncodableList MsStoreProduct::ToEncodableList() const {
  EncodableList list;
  list.reserve(8);
  list.push_back(EncodableValue(store_id_));
  list.push_back(EncodableValue(title_));
  list.push_back(EncodableValue(description_));
  list.push_back(EncodableValue(price_));
  list.push_back(EncodableValue(price_currency_code_));
  list.push_back(EncodableValue(formatted_price_));
  list.push_back(EncodableValue(product_kind_));
  list.push_back(EncodableValue(extended_json_data_));
  return list;
}

MsStoreProduct MsStoreProduct::FromEncodableList(const EncodableList& list) {
  MsStoreProduct decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]),
    std::get<std::string>(list[2]),
    std::get<std::string>(list[3]),
    std::get<std::string>(list[4]),
    std::get<std::string>(list[5]),
    std::get<std::string>(list[6]),
    std::get<std::string>(list[7]));
  return decoded;
}

bool MsStoreProduct::operator==(const MsStoreProduct& other) const {
  return PigeonInternalDeepEquals(store_id_, other.store_id_) && PigeonInternalDeepEquals(title_, other.title_) && PigeonInternalDeepEquals(description_, other.description_) && PigeonInternalDeepEquals(price_, other.price_) && PigeonInternalDeepEquals(price_currency_code_, other.price_currency_code_) && PigeonInternalDeepEquals(formatted_price_, other.formatted_price_) && PigeonInternalDeepEquals(product_kind_, other.product_kind_) && PigeonInternalDeepEquals(extended_json_data_, other.extended_json_data_);
}

bool MsStoreProduct::operator!=(const MsStoreProduct& other) const {
  return !(*this == other);
}

size_t MsStoreProduct::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(store_id_);
  result = result * 31 + PigeonInternalDeepHash(title_);
  result = result * 31 + PigeonInternalDeepHash(description_);
  result = result * 31 + PigeonInternalDeepHash(price_);
  result = result * 31 + PigeonInternalDeepHash(price_currency_code_);
  result = result * 31 + PigeonInternalDeepHash(formatted_price_);
  result = result * 31 + PigeonInternalDeepHash(product_kind_);
  result = result * 31 + PigeonInternalDeepHash(extended_json_data_);
  return result;
}

size_t PigeonInternalDeepHash(const MsStoreProduct& v) {
  return v.Hash();
}

// MsStoreProductResponse

MsStoreProductResponse::MsStoreProductResponse(int64_t extended_error)
 : extended_error_(extended_error) {}

MsStoreProductResponse::MsStoreProductResponse(
  const MsStoreProduct* product,
  int64_t extended_error)
 : product_(product ? std::make_unique<MsStoreProduct>(*product) : nullptr),
    extended_error_(extended_error) {}

MsStoreProductResponse::MsStoreProductResponse(const MsStoreProductResponse& other)
 : product_(other.product_ ? std::make_unique<MsStoreProduct>(*other.product_) : nullptr),
    extended_error_(other.extended_error_) {}

MsStoreProductResponse& MsStoreProductResponse::operator=(const MsStoreProductResponse& other) {
  product_ = other.product_ ? std::make_unique<MsStoreProduct>(*other.product_) : nullptr;
  extended_error_ = other.extended_error_;
  return *this;
}

const MsStoreProduct* MsStoreProductResponse::product() const {
  return product_.get();
}

void MsStoreProductResponse::set_product(const MsStoreProduct* value_arg) {
  product_ = value_arg ? std::make_unique<MsStoreProduct>(*value_arg) : nullptr;
}

void MsStoreProductResponse::set_product(const MsStoreProduct& value_arg) {
  product_ = std::make_unique<MsStoreProduct>(value_arg);
}


int64_t MsStoreProductResponse::extended_error() const {
  return extended_error_;
}

void MsStoreProductResponse::set_extended_error(int64_t value_arg) {
  extended_error_ = value_arg;
}


EncodableList MsStoreProductResponse::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(product_ ? CustomEncodableValue(*product_) : EncodableValue());
  list.push_back(EncodableValue(extended_error_));
  return list;
}

MsStoreProductResponse MsStoreProductResponse::FromEncodableList(const EncodableList& list) {
  MsStoreProductResponse decoded(
    std::get<int64_t>(list[1]));
  auto& encodable_product = list[0];
  if (!encodable_product.IsNull()) {
    decoded.set_product(std::any_cast<const MsStoreProduct&>(std::get<CustomEncodableValue>(encodable_product)));
  }
  return decoded;
}

bool MsStoreProductResponse::operator==(const MsStoreProductResponse& other) const {
  return PigeonInternalDeepEquals(product_, other.product_) && PigeonInternalDeepEquals(extended_error_, other.extended_error_);
}

bool MsStoreProductResponse::operator!=(const MsStoreProductResponse& other) const {
  return !(*this == other);
}

size_t MsStoreProductResponse::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(product_);
  result = result * 31 + PigeonInternalDeepHash(extended_error_);
  return result;
}

size_t PigeonInternalDeepHash(const MsStoreProductResponse& v) {
  return v.Hash();
}

// MsStorePurchaseResponse

MsStorePurchaseResponse::MsStorePurchaseResponse(
  const MsStorePurchaseStatus& status,
  int64_t extended_error)
 : status_(status),
    extended_error_(extended_error) {}

const MsStorePurchaseStatus& MsStorePurchaseResponse::status() const {
  return status_;
}

void MsStorePurchaseResponse::set_status(const MsStorePurchaseStatus& value_arg) {
  status_ = value_arg;
}


int64_t MsStorePurchaseResponse::extended_error() const {
  return extended_error_;
}

void MsStorePurchaseResponse::set_extended_error(int64_t value_arg) {
  extended_error_ = value_arg;
}


EncodableList MsStorePurchaseResponse::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(CustomEncodableValue(status_));
  list.push_back(EncodableValue(extended_error_));
  return list;
}

MsStorePurchaseResponse MsStorePurchaseResponse::FromEncodableList(const EncodableList& list) {
  MsStorePurchaseResponse decoded(
    std::any_cast<const MsStorePurchaseStatus&>(std::get<CustomEncodableValue>(list[0])),
    std::get<int64_t>(list[1]));
  return decoded;
}

bool MsStorePurchaseResponse::operator==(const MsStorePurchaseResponse& other) const {
  return PigeonInternalDeepEquals(status_, other.status_) && PigeonInternalDeepEquals(extended_error_, other.extended_error_);
}

bool MsStorePurchaseResponse::operator!=(const MsStorePurchaseResponse& other) const {
  return !(*this == other);
}

size_t MsStorePurchaseResponse::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(status_);
  result = result * 31 + PigeonInternalDeepHash(extended_error_);
  return result;
}

size_t PigeonInternalDeepHash(const MsStorePurchaseResponse& v) {
  return v.Hash();
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  ::flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<MsStorePurchaseStatus>(enum_arg_value));
      }
    case 130: {
        return CustomEncodableValue(MsStoreAppLicense::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 131: {
        return CustomEncodableValue(MsStoreProduct::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 132: {
        return CustomEncodableValue(MsStoreProductResponse::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 133: {
        return CustomEncodableValue(MsStorePurchaseResponse::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return ::flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  ::flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(MsStorePurchaseStatus)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<MsStorePurchaseStatus>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(MsStoreAppLicense)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(std::any_cast<MsStoreAppLicense>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(MsStoreProduct)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(std::any_cast<MsStoreProduct>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(MsStoreProductResponse)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(std::any_cast<MsStoreProductResponse>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(MsStorePurchaseResponse)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(std::any_cast<MsStorePurchaseResponse>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  ::flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by MsStoreHostApi.
const ::flutter::StandardMessageCodec& MsStoreHostApi::GetCodec() {
  return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `MsStoreHostApi` to handle messages through the `binary_messenger`.
void MsStoreHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  MsStoreHostApi* api) {
  MsStoreHostApi::SetUp(binary_messenger, api, "");
}

void MsStoreHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  MsStoreHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.ms_store_trial.MsStoreHostApi.getStoreProductForCurrentApp" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->GetStoreProductForCurrentApp([reply](ErrorOr<MsStoreProductResponse>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.ms_store_trial.MsStoreHostApi.requestCurrentAppPurchase" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->RequestCurrentAppPurchase([reply](ErrorOr<MsStorePurchaseResponse>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.ms_store_trial.MsStoreHostApi.restoreCurrentAppLicense" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->RestoreCurrentAppLicense();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue MsStoreHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue MsStoreHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
MsStoreFlutterApi::MsStoreFlutterApi(::flutter::BinaryMessenger* binary_messenger)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_("") {}

MsStoreFlutterApi::MsStoreFlutterApi(
  ::flutter::BinaryMessenger* binary_messenger,
  const std::string& message_channel_suffix)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_(message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "") {}

const ::flutter::StandardMessageCodec& MsStoreFlutterApi::GetCodec() {
  return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

void MsStoreFlutterApi::OnLicenseChanged(
  const MsStoreAppLicense& license_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.ms_store_trial.MsStoreFlutterApi.onLicenseChanged" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(license_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

}  // namespace ms_store_trial
