// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MS_STORE_API_G_H_
#define PIGEON_MS_STORE_API_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace ms_store_trial {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class MsStoreHostApi;
  friend class MsStoreFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class MsStorePurchaseStatus {
  kSucceed = 0,
  kAlreadyPurchased = 1,
  kNotPurchased = 2,
  kNetworkError = 3,
  kServerError = 4
};


// Generated class from Pigeon that represents data sent in messages.
class MsStoreLicense {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit MsStoreLicense(
    bool is_active,
    bool is_trial,
    bool is_trial_owned_by_this_user);

  // Constructs an object setting all fields.
  explicit MsStoreLicense(
    bool is_active,
    bool is_trial,
    bool is_trial_owned_by_this_user,
    const int64_t* expiration_timestamp);

  bool is_active() const;
  void set_is_active(bool value_arg);

  bool is_trial() const;
  void set_is_trial(bool value_arg);

  bool is_trial_owned_by_this_user() const;
  void set_is_trial_owned_by_this_user(bool value_arg);

  const int64_t* expiration_timestamp() const;
  void set_expiration_timestamp(const int64_t* value_arg);
  void set_expiration_timestamp(int64_t value_arg);

  bool operator==(const MsStoreLicense& other) const;
  bool operator!=(const MsStoreLicense& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static MsStoreLicense FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MsStoreHostApi;
  friend class MsStoreFlutterApi;
  friend class PigeonInternalCodecSerializer;
  bool is_active_;
  bool is_trial_;
  bool is_trial_owned_by_this_user_;
  std::optional<int64_t> expiration_timestamp_;
};


// Generated class from Pigeon that represents data sent in messages.
class MsStoreProduct {
 public:
  // Constructs an object setting all fields.
  explicit MsStoreProduct(
    const std::string& store_id,
    const std::string& description,
    const std::string& price);

  const std::string& store_id() const;
  void set_store_id(std::string_view value_arg);

  const std::string& description() const;
  void set_description(std::string_view value_arg);

  const std::string& price() const;
  void set_price(std::string_view value_arg);

  bool operator==(const MsStoreProduct& other) const;
  bool operator!=(const MsStoreProduct& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static MsStoreProduct FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MsStoreProductResponse;
  friend class MsStoreHostApi;
  friend class MsStoreFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string store_id_;
  std::string description_;
  std::string price_;
};


// Generated class from Pigeon that represents data sent in messages.
class MsStoreProductResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit MsStoreProductResponse(int64_t extended_error);

  // Constructs an object setting all fields.
  explicit MsStoreProductResponse(
    const MsStoreProduct* product,
    int64_t extended_error);

  ~MsStoreProductResponse() = default;
  MsStoreProductResponse(const MsStoreProductResponse& other);
  MsStoreProductResponse& operator=(const MsStoreProductResponse& other);
  MsStoreProductResponse(MsStoreProductResponse&& other) = default;
  MsStoreProductResponse& operator=(MsStoreProductResponse&& other) noexcept = default;
  const MsStoreProduct* product() const;
  void set_product(const MsStoreProduct* value_arg);
  void set_product(const MsStoreProduct& value_arg);

  int64_t extended_error() const;
  void set_extended_error(int64_t value_arg);

  bool operator==(const MsStoreProductResponse& other) const;
  bool operator!=(const MsStoreProductResponse& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static MsStoreProductResponse FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MsStoreHostApi;
  friend class MsStoreFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::unique_ptr<MsStoreProduct> product_;
  int64_t extended_error_;
};


// Generated class from Pigeon that represents data sent in messages.
class MsStorePurchaseResponse {
 public:
  // Constructs an object setting all fields.
  explicit MsStorePurchaseResponse(
    const MsStorePurchaseStatus& status,
    int64_t extended_error);

  const MsStorePurchaseStatus& status() const;
  void set_status(const MsStorePurchaseStatus& value_arg);

  int64_t extended_error() const;
  void set_extended_error(int64_t value_arg);

  bool operator==(const MsStorePurchaseResponse& other) const;
  bool operator!=(const MsStorePurchaseResponse& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static MsStorePurchaseResponse FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MsStoreHostApi;
  friend class MsStoreFlutterApi;
  friend class PigeonInternalCodecSerializer;
  MsStorePurchaseStatus status_;
  int64_t extended_error_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class MsStoreHostApi {
 public:
  MsStoreHostApi(const MsStoreHostApi&) = delete;
  MsStoreHostApi& operator=(const MsStoreHostApi&) = delete;
  virtual ~MsStoreHostApi() {}
  virtual void GetStoreProductForCurrentApp(std::function<void(ErrorOr<MsStoreProductResponse> reply)> result) = 0;
  virtual void RequestCurrentAppPurchase(std::function<void(ErrorOr<MsStorePurchaseResponse> reply)> result) = 0;
  virtual std::optional<FlutterError> RestoreCurrentAppLicense() = 0;

  // The codec used by MsStoreHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `MsStoreHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    MsStoreHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    MsStoreHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  MsStoreHostApi() = default;
};
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class MsStoreFlutterApi {
 public:
  MsStoreFlutterApi(::flutter::BinaryMessenger* binary_messenger);
  MsStoreFlutterApi(
    ::flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const ::flutter::StandardMessageCodec& GetCodec();
  void OnLicenseChanged(
    const MsStoreLicense& license,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
 private:
  ::flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace ms_store_trial
#endif  // PIGEON_MS_STORE_API_G_H_
