// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MS_STORE_API_G_H_
#define PIGEON_MS_STORE_API_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace ms_store_trial {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class MsStoreHostApi;
  friend class MsStoreFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// Generated class from Pigeon that represents data sent in messages.
class AppLicenseStruct {
 public:
  // Constructs an object setting all non-nullable fields.
  AppLicenseStruct();

  // Constructs an object setting all fields.
  explicit AppLicenseStruct(
    const bool* is_active,
    const bool* is_trial,
    const bool* is_trial_owned_by_this_user,
    const int64_t* trial_time_remaining,
    const int64_t* expiration_timestamp,
    const std::string* sku_store_id,
    const std::string* trial_unique_id,
    const std::string* extended_json_data);

  const bool* is_active() const;
  void set_is_active(const bool* value_arg);
  void set_is_active(bool value_arg);

  const bool* is_trial() const;
  void set_is_trial(const bool* value_arg);
  void set_is_trial(bool value_arg);

  const bool* is_trial_owned_by_this_user() const;
  void set_is_trial_owned_by_this_user(const bool* value_arg);
  void set_is_trial_owned_by_this_user(bool value_arg);

  const int64_t* trial_time_remaining() const;
  void set_trial_time_remaining(const int64_t* value_arg);
  void set_trial_time_remaining(int64_t value_arg);

  const int64_t* expiration_timestamp() const;
  void set_expiration_timestamp(const int64_t* value_arg);
  void set_expiration_timestamp(int64_t value_arg);

  const std::string* sku_store_id() const;
  void set_sku_store_id(const std::string_view* value_arg);
  void set_sku_store_id(std::string_view value_arg);

  const std::string* trial_unique_id() const;
  void set_trial_unique_id(const std::string_view* value_arg);
  void set_trial_unique_id(std::string_view value_arg);

  const std::string* extended_json_data() const;
  void set_extended_json_data(const std::string_view* value_arg);
  void set_extended_json_data(std::string_view value_arg);

  bool operator==(const AppLicenseStruct& other) const;
  bool operator!=(const AppLicenseStruct& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static AppLicenseStruct FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MsStoreHostApi;
  friend class MsStoreFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<bool> is_active_;
  std::optional<bool> is_trial_;
  std::optional<bool> is_trial_owned_by_this_user_;
  std::optional<int64_t> trial_time_remaining_;
  std::optional<int64_t> expiration_timestamp_;
  std::optional<std::string> sku_store_id_;
  std::optional<std::string> trial_unique_id_;
  std::optional<std::string> extended_json_data_;
};


// Generated class from Pigeon that represents data sent in messages.
class ProductPriceStruct {
 public:
  // Constructs an object setting all non-nullable fields.
  ProductPriceStruct();

  // Constructs an object setting all fields.
  explicit ProductPriceStruct(
    const std::string* formatted_price,
    const std::string* currency_code,
    const std::string* unformatted_price);

  const std::string* formatted_price() const;
  void set_formatted_price(const std::string_view* value_arg);
  void set_formatted_price(std::string_view value_arg);

  const std::string* currency_code() const;
  void set_currency_code(const std::string_view* value_arg);
  void set_currency_code(std::string_view value_arg);

  const std::string* unformatted_price() const;
  void set_unformatted_price(const std::string_view* value_arg);
  void set_unformatted_price(std::string_view value_arg);

  bool operator==(const ProductPriceStruct& other) const;
  bool operator!=(const ProductPriceStruct& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static ProductPriceStruct FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class ProductStruct;
  friend class MsStoreHostApi;
  friend class MsStoreFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> formatted_price_;
  std::optional<std::string> currency_code_;
  std::optional<std::string> unformatted_price_;
};


// Generated class from Pigeon that represents data sent in messages.
class ProductStruct {
 public:
  // Constructs an object setting all non-nullable fields.
  ProductStruct();

  // Constructs an object setting all fields.
  explicit ProductStruct(
    const std::string* store_id,
    const std::string* title,
    const std::string* description,
    const std::string* product_kind,
    const ProductPriceStruct* price,
    const std::string* extended_json_data);

  ~ProductStruct() = default;
  ProductStruct(const ProductStruct& other);
  ProductStruct& operator=(const ProductStruct& other);
  ProductStruct(ProductStruct&& other) = default;
  ProductStruct& operator=(ProductStruct&& other) noexcept = default;
  const std::string* store_id() const;
  void set_store_id(const std::string_view* value_arg);
  void set_store_id(std::string_view value_arg);

  const std::string* title() const;
  void set_title(const std::string_view* value_arg);
  void set_title(std::string_view value_arg);

  const std::string* description() const;
  void set_description(const std::string_view* value_arg);
  void set_description(std::string_view value_arg);

  const std::string* product_kind() const;
  void set_product_kind(const std::string_view* value_arg);
  void set_product_kind(std::string_view value_arg);

  const ProductPriceStruct* price() const;
  void set_price(const ProductPriceStruct* value_arg);
  void set_price(const ProductPriceStruct& value_arg);

  const std::string* extended_json_data() const;
  void set_extended_json_data(const std::string_view* value_arg);
  void set_extended_json_data(std::string_view value_arg);

  bool operator==(const ProductStruct& other) const;
  bool operator!=(const ProductStruct& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static ProductStruct FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class ProductResponseStruct;
  friend class MsStoreHostApi;
  friend class MsStoreFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> store_id_;
  std::optional<std::string> title_;
  std::optional<std::string> description_;
  std::optional<std::string> product_kind_;
  std::unique_ptr<ProductPriceStruct> price_;
  std::optional<std::string> extended_json_data_;
};


// Generated class from Pigeon that represents data sent in messages.
class ProductResponseStruct {
 public:
  // Constructs an object setting all non-nullable fields.
  ProductResponseStruct();

  // Constructs an object setting all fields.
  explicit ProductResponseStruct(
    const ProductStruct* product,
    const int64_t* extendeded_error);

  ~ProductResponseStruct() = default;
  ProductResponseStruct(const ProductResponseStruct& other);
  ProductResponseStruct& operator=(const ProductResponseStruct& other);
  ProductResponseStruct(ProductResponseStruct&& other) = default;
  ProductResponseStruct& operator=(ProductResponseStruct&& other) noexcept = default;
  const ProductStruct* product() const;
  void set_product(const ProductStruct* value_arg);
  void set_product(const ProductStruct& value_arg);

  const int64_t* extendeded_error() const;
  void set_extendeded_error(const int64_t* value_arg);
  void set_extendeded_error(int64_t value_arg);

  bool operator==(const ProductResponseStruct& other) const;
  bool operator!=(const ProductResponseStruct& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static ProductResponseStruct FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MsStoreHostApi;
  friend class MsStoreFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::unique_ptr<ProductStruct> product_;
  std::optional<int64_t> extendeded_error_;
};


// Generated class from Pigeon that represents data sent in messages.
class PurchaseResponseStruct {
 public:
  // Constructs an object setting all non-nullable fields.
  PurchaseResponseStruct();

  // Constructs an object setting all fields.
  explicit PurchaseResponseStruct(
    const int64_t* status,
    const int64_t* extended_error);

  const int64_t* status() const;
  void set_status(const int64_t* value_arg);
  void set_status(int64_t value_arg);

  const int64_t* extended_error() const;
  void set_extended_error(const int64_t* value_arg);
  void set_extended_error(int64_t value_arg);

  bool operator==(const PurchaseResponseStruct& other) const;
  bool operator!=(const PurchaseResponseStruct& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static PurchaseResponseStruct FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MsStoreHostApi;
  friend class MsStoreFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<int64_t> status_;
  std::optional<int64_t> extended_error_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class MsStoreHostApi {
 public:
  MsStoreHostApi(const MsStoreHostApi&) = delete;
  MsStoreHostApi& operator=(const MsStoreHostApi&) = delete;
  virtual ~MsStoreHostApi() {}
  virtual void GetPackageFamilyName(std::function<void(ErrorOr<std::string> reply)> result) = 0;
  virtual void GetStoreProductForCurrentApp(std::function<void(ErrorOr<ProductResponseStruct> reply)> result) = 0;
  virtual void RequestCurrentAppPurchase(std::function<void(ErrorOr<PurchaseResponseStruct> reply)> result) = 0;
  virtual std::optional<FlutterError> RestoreCurrentAppLicense() = 0;

  // The codec used by MsStoreHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `MsStoreHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    MsStoreHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    MsStoreHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  MsStoreHostApi() = default;
};
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class MsStoreFlutterApi {
 public:
  MsStoreFlutterApi(::flutter::BinaryMessenger* binary_messenger);
  MsStoreFlutterApi(
    ::flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const ::flutter::StandardMessageCodec& GetCodec();
  void OnLicenseChanged(
    const AppLicenseStruct& license,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
 private:
  ::flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace ms_store_trial
#endif  // PIGEON_MS_STORE_API_G_H_
