name: ms_store_trial_example
description: "Demonstrates how to use the ms_store_trial plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  ms_store_trial:
    # When depending on this package from a real application you should use:
    #   ms_store_trial: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.16.13

flutter:
  uses-material-design: true

# Here you can configure your MSIX packaging.
# Most of these values will be used to generate the AppxManifest.xml file.
#
# I recommend reading the official documentation in order to adapt it to your needs:
# https://pub.dev/packages/msix
msix_config:
  # Set to true for debugging sessions and false to release your app in Microsoft Store, or if you
  # are going to test on a computer/sandbox without the needed Visual Studio developer tools.
  debug: true
  # Using the same runner icon for simplicity.
  logo_path: windows/runner/resources/app_icon.ico
  # Should be true as we're uploading to Microsoft Store.
  store: true
  # Get these values from your Microsoft Partner dashboard.
  display_name: APP NAME
  publisher_display_name: DEVELOPER OR COMPANY NAME
  identity_name: APPNAME.DEVELOPERORCOMPANYNAME
  publisher: CN=YOUR-PUBLISHER-IDENTITY-HERE
  # Change the first three version numbers when releasing an update.
  msix_version: 1.1.0.0
