name: ms_store_trial
description: "Use Microsoft Store to offer a trial version of your Flutter app on Windows."
repository: https://github.com/setghm/flutter_ms_store_trial
version: 1.0.1

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: MsStoreTrialPluginCApi

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^26.3.3

topics:
  - in-app-purchase
  - payment

screenshots:
  - description: 'Example app running on a Windows machine'
    path: doc/ms_store_trial.gif
