// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class AppLicenseStruct {
  AppLicenseStruct({
    this.isActive,
    this.isTrial,
    this.isTrialOwnedByThisUser,
    this.trialTimeRemaining,
    this.expirationTimestamp,
    this.skuStoreId,
    this.trialUniqueId,
    this.extendedJsonData,
  });

  bool? isActive;

  bool? isTrial;

  bool? isTrialOwnedByThisUser;

  int? trialTimeRemaining;

  int? expirationTimestamp;

  String? skuStoreId;

  String? trialUniqueId;

  String? extendedJsonData;

  List<Object?> _toList() {
    return <Object?>[
      isActive,
      isTrial,
      isTrialOwnedByThisUser,
      trialTimeRemaining,
      expirationTimestamp,
      skuStoreId,
      trialUniqueId,
      extendedJsonData,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppLicenseStruct decode(Object result) {
    result as List<Object?>;
    return AppLicenseStruct(
      isActive: result[0] as bool?,
      isTrial: result[1] as bool?,
      isTrialOwnedByThisUser: result[2] as bool?,
      trialTimeRemaining: result[3] as int?,
      expirationTimestamp: result[4] as int?,
      skuStoreId: result[5] as String?,
      trialUniqueId: result[6] as String?,
      extendedJsonData: result[7] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppLicenseStruct || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isActive, other.isActive) && _deepEquals(isTrial, other.isTrial) && _deepEquals(isTrialOwnedByThisUser, other.isTrialOwnedByThisUser) && _deepEquals(trialTimeRemaining, other.trialTimeRemaining) && _deepEquals(expirationTimestamp, other.expirationTimestamp) && _deepEquals(skuStoreId, other.skuStoreId) && _deepEquals(trialUniqueId, other.trialUniqueId) && _deepEquals(extendedJsonData, other.extendedJsonData);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class ProductPriceStruct {
  ProductPriceStruct({
    this.formattedPrice,
    this.currencyCode,
    this.unformattedPrice,
  });

  String? formattedPrice;

  String? currencyCode;

  String? unformattedPrice;

  List<Object?> _toList() {
    return <Object?>[
      formattedPrice,
      currencyCode,
      unformattedPrice,
    ];
  }

  Object encode() {
    return _toList();  }

  static ProductPriceStruct decode(Object result) {
    result as List<Object?>;
    return ProductPriceStruct(
      formattedPrice: result[0] as String?,
      currencyCode: result[1] as String?,
      unformattedPrice: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ProductPriceStruct || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(formattedPrice, other.formattedPrice) && _deepEquals(currencyCode, other.currencyCode) && _deepEquals(unformattedPrice, other.unformattedPrice);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class ProductStruct {
  ProductStruct({
    this.storeId,
    this.title,
    this.description,
    this.productKind,
    this.price,
    this.extendedJsonData,
  });

  String? storeId;

  String? title;

  String? description;

  String? productKind;

  ProductPriceStruct? price;

  String? extendedJsonData;

  List<Object?> _toList() {
    return <Object?>[
      storeId,
      title,
      description,
      productKind,
      price,
      extendedJsonData,
    ];
  }

  Object encode() {
    return _toList();  }

  static ProductStruct decode(Object result) {
    result as List<Object?>;
    return ProductStruct(
      storeId: result[0] as String?,
      title: result[1] as String?,
      description: result[2] as String?,
      productKind: result[3] as String?,
      price: result[4] as ProductPriceStruct?,
      extendedJsonData: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ProductStruct || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(storeId, other.storeId) && _deepEquals(title, other.title) && _deepEquals(description, other.description) && _deepEquals(productKind, other.productKind) && _deepEquals(price, other.price) && _deepEquals(extendedJsonData, other.extendedJsonData);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class ProductResponseStruct {
  ProductResponseStruct({
    this.product,
    this.extendededError,
  });

  ProductStruct? product;

  int? extendededError;

  List<Object?> _toList() {
    return <Object?>[
      product,
      extendededError,
    ];
  }

  Object encode() {
    return _toList();  }

  static ProductResponseStruct decode(Object result) {
    result as List<Object?>;
    return ProductResponseStruct(
      product: result[0] as ProductStruct?,
      extendededError: result[1] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ProductResponseStruct || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(product, other.product) && _deepEquals(extendededError, other.extendededError);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class PurchaseResponseStruct {
  PurchaseResponseStruct({
    this.status,
    this.extendedError,
  });

  int? status;

  int? extendedError;

  List<Object?> _toList() {
    return <Object?>[
      status,
      extendedError,
    ];
  }

  Object encode() {
    return _toList();  }

  static PurchaseResponseStruct decode(Object result) {
    result as List<Object?>;
    return PurchaseResponseStruct(
      status: result[0] as int?,
      extendedError: result[1] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PurchaseResponseStruct || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(status, other.status) && _deepEquals(extendedError, other.extendedError);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is AppLicenseStruct) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is ProductPriceStruct) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is ProductStruct) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is ProductResponseStruct) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is PurchaseResponseStruct) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return AppLicenseStruct.decode(readValue(buffer)!);
      case 130:
        return ProductPriceStruct.decode(readValue(buffer)!);
      case 131:
        return ProductStruct.decode(readValue(buffer)!);
      case 132:
        return ProductResponseStruct.decode(readValue(buffer)!);
      case 133:
        return PurchaseResponseStruct.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class MsStoreHostApi {
  /// Constructor for [MsStoreHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MsStoreHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<String> getPackageFamilyName() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ms_store_trial.MsStoreHostApi.getPackageFamilyName$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<ProductResponseStruct> getStoreProductForCurrentApp() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ms_store_trial.MsStoreHostApi.getStoreProductForCurrentApp$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ProductResponseStruct;
  }

  Future<PurchaseResponseStruct> requestCurrentAppPurchase() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ms_store_trial.MsStoreHostApi.requestCurrentAppPurchase$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PurchaseResponseStruct;
  }

  Future<void> restoreCurrentAppLicense() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ms_store_trial.MsStoreHostApi.restoreCurrentAppLicense$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class MsStoreFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onLicenseChanged(AppLicenseStruct license);

  static void setUp(MsStoreFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ms_store_trial.MsStoreFlutterApi.onLicenseChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AppLicenseStruct arg_license = args[0]! as AppLicenseStruct;
          try {
            api.onLicenseChanged(arg_license);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
