// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum MsStorePurchaseStatus {
  succeed,
  alreadyPurchased,
  notPurchased,
  networkError,
  serverError,
}

class MsStoreLicense {
  MsStoreLicense({
    required this.isActive,
    required this.isTrial,
    required this.isTrialOwnedByThisUser,
    this.expirationTimestamp,
  });

  bool isActive;

  bool isTrial;

  bool isTrialOwnedByThisUser;

  int? expirationTimestamp;

  List<Object?> _toList() {
    return <Object?>[
      isActive,
      isTrial,
      isTrialOwnedByThisUser,
      expirationTimestamp,
    ];
  }

  Object encode() {
    return _toList();  }

  static MsStoreLicense decode(Object result) {
    result as List<Object?>;
    return MsStoreLicense(
      isActive: result[0]! as bool,
      isTrial: result[1]! as bool,
      isTrialOwnedByThisUser: result[2]! as bool,
      expirationTimestamp: result[3] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MsStoreLicense || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isActive, other.isActive) && _deepEquals(isTrial, other.isTrial) && _deepEquals(isTrialOwnedByThisUser, other.isTrialOwnedByThisUser) && _deepEquals(expirationTimestamp, other.expirationTimestamp);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class MsStoreProduct {
  MsStoreProduct({
    required this.storeId,
    required this.description,
    required this.price,
  });

  String storeId;

  String description;

  String price;

  List<Object?> _toList() {
    return <Object?>[
      storeId,
      description,
      price,
    ];
  }

  Object encode() {
    return _toList();  }

  static MsStoreProduct decode(Object result) {
    result as List<Object?>;
    return MsStoreProduct(
      storeId: result[0]! as String,
      description: result[1]! as String,
      price: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MsStoreProduct || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(storeId, other.storeId) && _deepEquals(description, other.description) && _deepEquals(price, other.price);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class MsStoreProductResponse {
  MsStoreProductResponse({
    this.product,
    required this.extendedError,
  });

  MsStoreProduct? product;

  int extendedError;

  List<Object?> _toList() {
    return <Object?>[
      product,
      extendedError,
    ];
  }

  Object encode() {
    return _toList();  }

  static MsStoreProductResponse decode(Object result) {
    result as List<Object?>;
    return MsStoreProductResponse(
      product: result[0] as MsStoreProduct?,
      extendedError: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MsStoreProductResponse || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(product, other.product) && _deepEquals(extendedError, other.extendedError);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class MsStorePurchaseResponse {
  MsStorePurchaseResponse({
    required this.status,
    required this.extendedError,
  });

  MsStorePurchaseStatus status;

  int extendedError;

  List<Object?> _toList() {
    return <Object?>[
      status,
      extendedError,
    ];
  }

  Object encode() {
    return _toList();  }

  static MsStorePurchaseResponse decode(Object result) {
    result as List<Object?>;
    return MsStorePurchaseResponse(
      status: result[0]! as MsStorePurchaseStatus,
      extendedError: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MsStorePurchaseResponse || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(status, other.status) && _deepEquals(extendedError, other.extendedError);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is MsStorePurchaseStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is MsStoreLicense) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is MsStoreProduct) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is MsStoreProductResponse) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is MsStorePurchaseResponse) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : MsStorePurchaseStatus.values[value];
      case 130:
        return MsStoreLicense.decode(readValue(buffer)!);
      case 131:
        return MsStoreProduct.decode(readValue(buffer)!);
      case 132:
        return MsStoreProductResponse.decode(readValue(buffer)!);
      case 133:
        return MsStorePurchaseResponse.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class MsStoreHostApi {
  /// Constructor for [MsStoreHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MsStoreHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<MsStoreProductResponse> getStoreProductForCurrentApp() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ms_store_trial.MsStoreHostApi.getStoreProductForCurrentApp$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MsStoreProductResponse;
  }

  Future<MsStorePurchaseResponse> requestCurrentAppPurchase() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ms_store_trial.MsStoreHostApi.requestCurrentAppPurchase$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MsStorePurchaseResponse;
  }

  Future<void> restoreCurrentAppLicense() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ms_store_trial.MsStoreHostApi.restoreCurrentAppLicense$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class MsStoreFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onLicenseChanged(MsStoreLicense license);

  static void setUp(MsStoreFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ms_store_trial.MsStoreFlutterApi.onLicenseChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final MsStoreLicense arg_license = args[0]! as MsStoreLicense;
          try {
            api.onLicenseChanged(arg_license);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
